# Generated by Django 2.2.19 on 2021-03-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20210320_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publicated',
            new_name='is_publicated',
        ),
    ]
