# Generated by Django 2.2.19 on 2021-03-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20210320_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sort_order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='порядок сортировки'),
        ),
    ]
