# Generated by Django 2.2.19 on 2021-03-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(default=None, max_length=254, null=True, verbose_name='имя опции')),
                ('option_value', models.CharField(default=None, max_length=254, null=True, verbose_name='значение опции')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
