# Generated by Django 2.2.19 on 2021-03-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_options', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'опция проекта', 'verbose_name_plural': 'опции проекта'},
        ),
        migrations.AddField(
            model_name='option',
            name='slug',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='option',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='добавлено'),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_name',
            field=models.CharField(default=None, max_length=254, null=True, unique=True, verbose_name='имя опции'),
        ),
        migrations.AlterField(
            model_name='option',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
    ]
